# fly.toml file generated for hunter-proto-hackers on 2023-03-29T08:55:26-06:00

app = "hunter-proto-hackers"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "den"
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 1024
