# fly.toml file generated for hunter-proto-hackers on 2023-03-29T08:55:26-06:00

app = "hunter-proto-hackers"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "den"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [[services.ports]]
    port = 1024
